command_timeout = 200
add_newline = false
# A minimal left prompt
format = """$directory$character"""
palette = "catppuccin_mocha"
# move the rest of the prompt to the right
right_format = """$all"""

[directory.substitutions]
'~/tests/starship-custom' = 'work-project'

[directory]
truncate_to_repo = true
format = '[$path/]($style)[$read_only]($read_only_style)'
read_only = " "
style = 'blue'
truncation_length = 4
truncation_symbol = "…/"

[character]
success_symbol = ""
vicmd_symbol = ""
error_symbol = "󰩈"

[git_state]
disabled = false

[git_branch]
format = "on [$symbol$branch](bold purple) "

[git_status]
disabled = false
format = '([$all_status]($style))'
conflicted = "([⚠️ ${count}](bold red) )"
ahead = "([⟫${count}])"
behind = "([⟪${count}])"
stashed = "([↪ ${count}](bold red)) "
modified = "([柳${count}](bold yellow) )"
staged = "([ ${count}](bold green) )"
renamed = "([⇆ ${count}](bold blue) )"
deleted = "([ ${count}](bold red) )"
untracked ="([ ${count}](dimmed red) )"

[package]
disabled = true

[gcloud]
disabled = true

[golang]
format = '[ ](bold cyan)'

[jobs]
symbol = ''
format = '[$symbol $number ]($style)'
symbol_threshold = 1
number_threshold = 1
style = 'bold blue'

[docker_context]
disabled = true

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
