github.com:
    user: charles-russell_ukg
    git_protocol: ssh
    users:
        charles-russell:
        charles-russell_ukg:
github.dev.us.corp:
    user: charles-russell
    git_protocol: ssh
    users:
        charles-russell:
